version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: feAdminMock
      POSTGRES_PASSWORD: passwordMock
      POSTGRES_DB: dev_fecamp18
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
